---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: podinfod
          env:
            - name: PODINFO_UI_COLOR
              value: "green"
